name: Auto Graded Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio pytest

    - name: Run tests
      run: |
        pytest regression_test.py

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results
        path: test-results/

    - name: Archive code coverage results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage/

    - name: Generate coverage report
      run: |
        pip install coverage
        coverage run -m pytest
        coverage html
        coverage xml
        coverage report
      continue-on-error: true

    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: coverage-html-report
        path: htmlcov/
